POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username": "Udoy Shaha",
    "email": "udoysaha103@gmail.com",
    "password": "Test@321"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "udoysaha103@gmail.com",
    "password": "Test@321"
}
###
POST http://localhost:5000/auth/login

###
GET http://localhost:5000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NkNWU1NzE1YTNmZTU1MjY1OGMxNjEiLCJpYXQiOjE3NDE1MTIyODMsImV4cCI6MTc0MTk0NDI4M30.EaVfqYlm9UQYiriNgKUiJCyiZMji6iMrwq6GHlUUmYs
###
POST http://localhost:5000/user/getVerificationMail 
Content-Type: application/json

{
    "email": "xyz@xasdjfiasdfasdy.xyz"
}
###
GET http://localhost:5000/user/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhaXNhbGhhd2xhZGVyLm9iQGdtYWlsLmNvbSIsImNvZGUiOiIzYUxsNHJndCIsImlhdCI6MTc0MTcyNjA0NCwiZXhwIjoxNzQxNzI2MzQ0fQ.0Ji7PSWdvivtSA8bjhBRmlVJCAWxy7YdcjnV7kGSo78