POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username": "Udoy Shaha",
    "email": "udoysaha103@gmail.com",
    "password": "Test@321"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "udoysaha103@gmail.com",
    "password": "Test@321"
}
###
POST http://localhost:5000/auth/login

###
GET http://localhost:5000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2NkNWU1NzE1YTNmZTU1MjY1OGMxNjEiLCJpYXQiOjE3NDE1MTIyODMsImV4cCI6MTc0MTk0NDI4M30.EaVfqYlm9UQYiriNgKUiJCyiZMji6iMrwq6GHlUUmYs
###
POST http://localhost:5000/user/getVerificationMail 
Content-Type: application/json

{
    "email": "xyz@xasdjfiasdfasdy.xyz"
}
###
POST http://localhost:5000/user/verify 
Content-Type: application/json

{
    "email": "udoysaha103@gmail.com", 
    "code": "198765"
}


###
POST http://localhost:5000/KOLregister/submitVerificationRequest
Content-Type: application/json

{
    "twitterName": "udoysaha103",
    "IRLname": "Udoy Shaha",
    "country": "Bangladesh",
    "photoPath": "https://pbs.twimg.com/profile_images/1441160340136827393/1J9J9J9J_400x400.jpg",
    "walletAddress": "CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o",
    "showAddress": "true",
    "signID": "1234567890",
    "twitterLink": "https://twitter.com/udoysaha103",
    "discordLink": "https://discord.gg/udoysaha103",
    "telegramLink": "https://t.me/udoysaha103",
    "youtubeLink": "https://youtube.com/udoysaha103",
    "generatedCode": "123456"
}
###

POST http://localhost:5000/KOLregister/verifyKOL
Content-Type: application/json

{
    "KOL_id" : "67d0a8f6afff95227ae284c7"
}